# Generated by Django 5.2.16 on 2026-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("service", "date", "start"),
                name="unique_active_appointment_slot",
            ),
        ),
    ]
