# Generated by Django 5.2.16 on 2026-07-17 19:08

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_demo_admin(apps, schema_editor):
    user_model = apps.get_model("auth", "User")
    user, _ = user_model.objects.get_or_create(username="admin")
    user.password = make_password("devschedule")
    user.is_active = True
    user.is_staff = True
    user.save(update_fields=["password", "is_active", "is_staff"])


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_appointment_unique_active_appointment_slot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_active_appointment_slot",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("date", "start"),
                name="unique_active_global_appointment_slot",
            ),
        ),
        migrations.RunPython(create_demo_admin, migrations.RunPython.noop),
    ]
